"""
app.py — Flask API server for iPrep
Run: python3 app.py

Models:
  - Question Generation : FLAN-T5-small (google/flan-t5-small)
  - Answer Evaluation   : XGBoost (interview_quality_classifier.pkl)
"""
from flask import Flask, request, jsonify
from flask_cors import CORS

app = Flask(__name__)
CORS(app)

from evaluator import evaluate_answer
from question_generator import generate_questions

# ── Routes ────────────────────────────────────────────────────────────────────

@app.route("/api/health")
def health():
    return jsonify({
        "status": "ok",
        "question_model": "FLAN-T5-small (google/flan-t5-small)",
        "evaluation_model": "XGBoost interview_quality_classifier.pkl",
    })


@app.route("/api/metadata")
def metadata():
    """Return available filter options for the practice arena."""
    return jsonify({
        "roles": [
            "Frontend Developer",
            "Backend Engineer",
            "Full Stack Developer",
            "DevOps Engineer",
            "System Designer",
            "DSA / Competitive Programming",
        ],
        "categories": ["DSA", "System Design", "Behavioral", "Technical Concepts"],
        "difficulties": ["Easy", "Medium", "Hard"],
        "total": None,  # Dynamic — generated by FLAN-T5
    })


@app.route("/api/questions")
def questions():
    """
    Generate interview questions using FLAN-T5-small.
    Query params: role, category, difficulty, limit (max 15)
    """
    role       = request.args.get("role", "All")
    category   = request.args.get("category", "All")
    difficulty = request.args.get("difficulty", "Medium")
    limit      = min(int(request.args.get("limit", 10)), 15)

    qs = generate_questions(role=role, category=category, difficulty=difficulty, n=limit)
    return jsonify({"questions": qs, "total": len(qs)})


@app.route("/api/evaluate", methods=["POST"])
def evaluate():
    """
    Evaluate an answer using the XGBoost interview quality classifier.
    Body: {answer, question, category}
    """
    data     = request.get_json(force=True)
    answer   = data.get("answer", "").strip()
    question = data.get("question", "").strip()
    category = data.get("category", "")

    if not question:
        return jsonify({"error": "Question is required"}), 400

    result = evaluate_answer(answer, question, category)
    return jsonify(result)


@app.route("/api/sessions")
def sessions():
    """
    Session history is stored in the user's browser localStorage.
    This endpoint returns an empty list — the frontend manages its own data.
    """
    return jsonify({"sessions": [], "total": 0})


@app.route("/api/leaderboard")
def leaderboard():
    """
    Leaderboard requires persistent user accounts.
    Returns an empty list until authentication is implemented.
    """
    period      = request.args.get("period", "weekly")
    role_filter = request.args.get("role", "All")
    return jsonify({"leaderboard": [], "period": period, "total": 0})


@app.route("/api/progress")
def progress():
    """
    Progress data is derived from localStorage on the frontend.
    Returns an empty structure so the frontend falls back to its own data.
    """
    return jsonify({
        "total_questions":    0,
        "avg_score":          0,
        "best_category":      None,
        "sessions_completed": 0,
        "session_scores":     [],
        "radar":              {},
    })


if __name__ == "__main__":
    print("🚀 iPrep API running at http://localhost:8000")
    print("   Questions : FLAN-T5-small")
    print("   Evaluation: XGBoost classifier")
    app.run(port=8000, debug=True)
