"""
app.py — Flask API server for iPrep
Run: python3 app.py

Models:
  - Question Generation : FLAN-T5-small (google/flan-t5-small)
  - Answer Evaluation   : XGBoost (interview_quality_classifier.pkl)
"""
from flask import Flask, request, jsonify
from flask_cors import CORS

app = Flask(__name__)
CORS(app)

from evaluator import evaluate_answer
import requests
import os

# ── Routes ────────────────────────────────────────────────────────────────────

@app.route("/api/health")
def health():
    return jsonify({
        "status": "ok",
        "question_model": "FLAN-T5-small (google/flan-t5-small)",
        "evaluation_model": "XGBoost interview_quality_classifier.pkl",
    })


@app.route("/api/metadata")
def metadata():
    """Return available filter options for the practice arena."""
    return jsonify({
        "roles": [
            "Frontend Developer",
            "Backend Engineer",
            "Full Stack Developer",
            "DevOps Engineer",
            "System Designer",
            "DSA / Competitive Programming",
        ],
        "categories": ["DSA", "System Design", "Behavioral", "Technical Concepts"],
        "difficulties": ["Easy", "Medium", "Hard"],
        "total": None,  # Dynamic — generated by FLAN-T5
    })


@app.route("/api/questions")
def questions():
    """
    Proxy request to external FLAN-T5 Microservice.
    Query params: role, category, difficulty, limit
    """
    role       = request.args.get("role", "All")
    category   = request.args.get("category", "All")
    difficulty = request.args.get("difficulty", "Medium")
    limit      = min(int(request.args.get("limit", 10)), 15)

    flan_service_url = os.environ.get("FLAN_SERVICE_URL")
    if not flan_service_url:
        return jsonify({"error": "FLAN_SERVICE_URL not configured. Please set it in .env"}), 500

    try:
        response = requests.get(
            f"{flan_service_url}/api/generate",
            params={"role": role, "category": category, "difficulty": difficulty, "limit": limit},
            timeout=120
        )
        response.raise_for_status()
        return jsonify(response.json())
    except Exception as e:
        app.logger.error(f"Failed to fetch questions from FLAN-T5 service: {e}")
        return jsonify({"error": "Failed to generate questions. Model service might be down."}), 502


@app.route("/api/evaluate", methods=["POST"])
def evaluate():
    """
    Evaluate an answer using the XGBoost interview quality classifier.
    Body: {answer, question, category}
    """
    data     = request.get_json(force=True)
    answer   = data.get("answer", "").strip()
    question = data.get("question", "").strip()
    category = data.get("category", "")

    if not question:
        return jsonify({"error": "Question is required"}), 400

    result = evaluate_answer(answer, question, category)
    return jsonify(result)


@app.route("/api/sessions")
def sessions():
    """
    Session history is stored in the user's browser localStorage.
    This endpoint returns an empty list — the frontend manages its own data.
    """
    return jsonify({"sessions": [], "total": 0})


@app.route("/api/leaderboard")
def leaderboard():
    """
    Dynamically calculate the leaderboard by aggregating user sessions.
    """
    period = request.args.get("period", "weekly")
    role_filter = request.args.get("role", "All")
    
    try:
        from supabase_client import get_supabase_client
        supabase = get_supabase_client()
        
        # 1. Fetch users
        users_response = supabase.table("users").select("*").execute()
        users = users_response.data
        
        # 2. Fetch sessions
        sessions_response = supabase.table("sessions").select("*").execute()
        sessions = sessions_response.data
        
        # 3. Aggregate data
        leaderboard_data = []
        for user in users:
            user_sessions = [s for s in sessions if s.get("user_id") == user.get("id")]
            
            # Apply role filter if not "All"
            if role_filter != "All" and user.get("role_focus") != role_filter:
                continue
                
            session_count = len(user_sessions)
            if session_count == 0:
                continue # Skip users with no sessions
                
            avg_score = sum(s.get("score", 0) for s in user_sessions) / session_count
            
            leaderboard_data.append({
                "id": user.get("id"),
                "username": user.get("username", "Unknown"),
                "role": user.get("role_focus", "Unknown"),
                "sessions": session_count,
                "avg_score": round(avg_score),
                "streak": user.get("streak", 0),
                "badge": user.get("top_badge", "Good")
            })
            
        # 4. Sort by avg_score (descending) and sessions (descending)
        leaderboard_data.sort(key=lambda x: (x["avg_score"], x["sessions"]), reverse=True)
        
        # 5. Assign ranks
        for i, entry in enumerate(leaderboard_data):
            entry["rank"] = i + 1
            
        return jsonify(leaderboard_data)
        
    except Exception as e:
        print(f"Error fetching leaderboard: {e}")
        return jsonify([])


@app.route("/api/progress")
def progress():
    """
    Progress data is derived from localStorage on the frontend.
    Returns an empty structure so the frontend falls back to its own data.
    """
    return jsonify({
        "total_questions":    0,
        "avg_score":          0,
        "best_category":      None,
        "sessions_completed": 0,
        "session_scores":     [],
        "radar":              {},
    })


if __name__ == "__main__":
    print("🚀 iPrep API running at http://localhost:8000")
    print("   Questions : FLAN-T5-small")
    print("   Evaluation: XGBoost classifier")
    app.run(port=8000, debug=True)
